version: '3'

services:
  ourlib-cont:
    image: ourlib-img:pre-test
    container_name: ourlib-cont
    ports:
      - "8000:8000"
    restart: unless-stopped
    networks:
      - art-networkkkkkkkkkkkkk

networks:
  art-network:
    driver: bridge